Importaciones

In [5]:
import keras
import tensorflow as tf

Lista de frases

In [10]:
frases = ['Hola mundo',
          'Hola a todos',
          'Hola a todo el mundo',
          'Buena día, como estas hoy']

Diccionario de tokens

In [13]:
tokenizer = tf.keras.preprocessing.text.Tokenizer(num_words = 10,
                                                  oov_token="<OOV>")
tokenizer.fit_on_texts(frases)
word_index = tokenizer.word_index
print('word_index =', word_index)

word_index = {'<OOV>': 1, 'hola': 2, 'mundo': 3, 'a': 4, 'todos': 5, 'todo': 6, 'el': 7, 'buena': 8, 'día': 9, 'como': 10, 'estas': 11, 'hoy': 12}


Generación de secuencias tokenizadas

In [14]:
secuencias = tokenizer.texts_to_sequences(frases)
print('secuencias =', secuencias)

secuencias = [[2, 3], [2, 4, 5], [2, 4, 6, 7, 3], [8, 9, 1, 1, 1]]


Llenado de secuencias a una longitud uniforme

In [15]:
relleno = keras.preprocessing.sequence.pad_sequences(secuencias)
print('rellena =\n', relleno)

rellena =
 [[0 0 0 2 3]
 [0 0 2 4 5]
 [2 4 6 7 3]
 [8 9 1 1 1]]


Truncamiento

In [17]:
relleno = keras.preprocessing.sequence.pad_sequences(secuencias,
                                                     padding = 'post',
                                                     truncating = 'post')
print('rellena =\n', relleno)

rellena =
 [[2 3 0 0 0]
 [2 4 5 0 0]
 [2 4 6 7 3]
 [8 9 1 1 1]]
